* [32mmaster[m
  user/bazoabi/AddNewTaskUI[m
  user/bazoabi/AddThemeColorsAndDecorations[m
  user/bazoabi/ApplyExternalGlobalFont[m
  user/bazoabi/CreateTodoComponent[m
  user/bazoabi/CreateTodoListUiStructure[m
  user/bazoabi/CreateTodosList[m
  user/bazoabi/DeployToGitHuBPages[m
  user/bazoabi/ExtractDialogsComponents[m
  user/bazoabi/FilteringDisplayTodos[m
  user/bazoabi/FixAppElementsCentering[m
  user/bazoabi/HandleTodoDeletion[m
  user/bazoabi/HandleTodoUpdate[m
  user/bazoabi/ImplementAddingNewTodoTaskLogic[m
  user/bazoabi/InitNpmPackages[m
  user/bazoabi/MakeTodosGlobalContext[m
  user/bazoabi/MovingDialogsModalsUpToParent[m
  user/bazoabi/ToggleCompletedTodoBtn[m
  user/bazoabi/UpdateLocalStorage[m
  user/bazoabi/UseMemoForFilteredArraysComputation[m
